# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_reports', '0016_auto_20160327_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(default='New Partner Organization', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='submit_reports.Course'),
        ),
        migrations.AlterField(
            model_name='submitreport',
            name='service_type',
            field=models.CharField(choices=[('DIRECT_SERVICE', 'Direct Service'), ('TRAINING', 'Training'), ('IND_RESEARCH', 'Individual Research'), ('TEAM_RESEARCH', 'Team Research')], max_length=14, null=True),
        ),
    ]
